export enum APIErrorCodes {
  ENTITY_ALREADY_EXISTS = 'ENTITY_ALREADY_EXISTS',
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
  REQUEST_VALIDATION_ERROR = 'REQUEST_VALIDATION_ERROR',
  FORBIDDEN_ERROR = 'FORBIDDEN',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  UNAUTHORIZED_ERROR = 'UNAUTHORIZED',
  SAME_PASSWORD = 'SAME_PASSWORD',
  OLD_PASSWORD_INVALID = 'OLD_PASSWORD_INVALID',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  USERNAME_ALREADY_EXIST = 'ENTITY_ALREADY_EXISTS',
  USERNAME_CHANGES_COUNT_EXCEEDED = 'USERNAME_CHANGES_COUNT_EXCEEDED',
}

export enum E2EErrors {
  MIN_LENGTH_PASSWORD_ERROR = 'Password must be at least 8 characters long',
  MAX_LENGTH_PASSWORD_ERROR = 'Password must be up to 20 characters long',
  EMPTY_EMAIL_ERROR = 'Please enter your email address',
  EMPTY_PASSWORD_ERROR = 'Please enter your password',
  WRONG_SYMBOLS_PASSWORD_ERROR = 'Use a stronger password: include uppercase letters, numbers, and symbols',
  EMAIL_FORMAT_ERROR = 'Enter a valid email address (e.g. name@example.com)',
  NEW_PASSWORD_REQUIRED_ERROR = 'The new password is required',
  SAME_PASSWORD_ERROR = 'The new password must differ from the old one',
  INCORRECT_OLD_PASSWORD_ERROR = 'The old password is not correct',
  COUNTRY_REQUIRED_ERROR = 'Please select a country',
  NO_ACCOUNT_ERROR = 'No account found with this email and password',
  TOKEN_INVALID_ERROR = 'Token invalid',
  PASSWORD_DO_NOT_MATCH_ERROR = 'Passwords do not match',
  CHANGE_PASSWORD_THE_SAME_PASSWORD = 'same password: new password cannot be the same as the old password',
  TOKEN_BAD_REQUEST = 'bad request: reset token is invalid or expired',
}

export enum APIErrorMessages {
  TOO_MANY_REQUESTS_ERROR = 'Too many requests',
  EMAIL_FIELD_REQUIRED_ERROR = "validation error: The 'email' field is required",
  EMAIL_VALIDATION_ERROR = "validation error: The 'email' field must be a valid email",
  EMAIL_FIELD_MAX_SYMBOLS_ERROR = "validation error: The 'email' field must be at most 320 characters long",
  TOKEN_FIELD_REQUIRED_ERROR = "validation error: The 'token' field is required",
  TOKEN_EXPIRED_ERROR = 'bad request: reset token is invalid or expired',
  TOKEN_EXPIRED_2_ERROR = 'token is expired',
  TOKEN_UNVERIFIED_ERROR = 'token is unverifiable',
  TOKEN_MALFORMED_ERROR = 'token is malformed: token contains an invalid number of segments',
  OLD_PASSWORD_INVALID_ERROR = 'invalid old password: invalid credentials',
  NEW_PASSWORD_FILED_REQUIRED_ERROR = "validation error: The 'new_password' field is required",
  NEW_PASSWORD_MIN_SYMBOLS_ERROR = "validation error: The 'new_password' field must be at least 8 characters long",
  NEW_PASSWORD_MAX_SYMBOLS_ERROR = "validation error: The 'new_password' field must be at most 20 characters long",
  NEW_PASSWORD_VALIDATION_ERROR = "validation error: The 'new_password' field must be at least 8 characters long, include at least one uppercase letter, one lowercase letter, one digit, and one special character, and must contain only English letters, digits, or special characters",
  NEW_PASSWORD_SAME_ERROR = 'same password: new password cannot be the same as the old password',
  PASSWORD_FILED_REQUIRED_ERROR = "validation error: The 'password' field is required",
  PASSWORD_MIN_SYMBOLS_ERROR = "validation error: The 'password' field must be at least 8 characters long",
  PASSWORD_MAX_SYMBOLS_ERROR = "validation error: The 'password' field must be at most 20 characters long",
  PASSWORD_VALIDATION_ERROR = "validation error: The 'password' field must be at least 8 characters long, include at least one uppercase letter, one lowercase letter, one digit, and one special character, and must contain only English letters, digits, or special characters",
  CREDENTIALS_ALREADY_EXIST_ERROR = 'credentials for user already exists',
  CREDENTIALS_NOT_FOUND_ERROR = 'credentials for user not found',
  USERNAME_VALIDATION_ERROR = "validation error: The 'username' field must be 4-16 characters long, start from a letter and must contain only digits, underscore and English letters",
  USERNAME_CHANGE_ATTEMPTS_ERROR = 'No available changes left',
  USERNAME_ALREADY_EXIST_ERROR = 'Username already exists',
  INVALID_CREDENTIALS_ERROR = 'Invalid credentials',
  INTERNAL_SERVER_ERROR = 'Internal server error',
  INVALID_REQUEST_ERROR = 'Invalid request.',
}
